apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: ums-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: ums-backend
  template:
    metadata:
      labels:
        app: ums-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
          env:
            - name: PORT
              value: "{{ .Values.backend.service.targetPort }}"
            - name: NODE_ENV
              value: "production"
            - name: CORS_ORIGIN
              value: "{{ .Values.backend.env.corsOrigin }}"
            - name: ENABLE_METRICS
              value: "{{ ternary "true" "false" .Values.backend.env.enableMetrics }}"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: JWT_SECRET
            - name: ADMIN_INVITE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: ADMIN_INVITE_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DATABASE_URL
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: MONGODB_URI
          resources: {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ums-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: ums-backend
spec:
  selector:
    app: ums-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
