apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: ums-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: ums-frontend
  template:
    metadata:
      labels:
        app: ums-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          env:
            - name: VITE_API_URL
              value: "{{ .Values.frontend.env.apiUrl }}"
          resources: {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ums-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: ums-frontend
spec:
  selector:
    app: ums-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
