version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ums_auth
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongodata:/data/db]

  backend:
    build: ../backend
    environment:
      PORT: 4000
      NODE_ENV: development
      JWT_SECRET: devsecret
      JWT_EXPIRES_IN: 30m
      CORS_ORIGIN: http://localhost:5173
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ums_auth?schema=public
      MONGODB_URI: mongodb://mongo:27017/ums
      ENABLE_METRICS: 'true'
      ADMIN_INVITE_SECRET: let-admins-in
    ports: ["4000:4000"]
    depends_on: [postgres, mongo]

  frontend:
    build: ../frontend
    environment:
      VITE_API_URL: http://localhost:4000
    ports: ["5173:80"]
    depends_on: [backend]

volumes:
  pgdata: {}
  mongodata: {}