apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ums
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: <your-registry>/ums-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ums-secrets
                  key: JWT_SECRET
            - name: ADMIN_INVITE_SECRET
              valueFrom:
                secretKeyRef:
                  name: ums-secrets
                  key: ADMIN_INVITE_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ums-secrets
                  key: DATABASE_URL
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: ums-secrets
                  key: MONGODB_URI
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: ums-config
                  key: CORS_ORIGIN
            - name: ENABLE_METRICS
              valueFrom:
                configMapKeyRef:
                  name: ums-config
                  key: ENABLE_METRICS
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ums
spec:
  selector: { app: backend }
  ports:
    - port: 80
      targetPort: 4000